name: my_gpt_fast
channels:
  - pytorch-nightly
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch
  - sentencepiece
  - tiktoken
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - scikit-build
  - ipython
  - pip
  - pip:
    - -e kernel_ext
