name: my_gpt_fast
channels:
  # - pytorch
  # - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - sentencepiece
  - tiktoken
  - scikit-build
  - ipython
  - pip
  - nvtx
  - pip:
    # - torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu124
    - --index-url https://download.pytorch.org/whl/nightly/cu124
    - torch
    - torchvision
    - torchaudio
  - pip:
    - grouped_gemm
  - pip:
    - -e kernel_ext
